# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.5.1"
wally = "UpliftGames/wally@0.3.2"
darklua = "seaofvoices/darklua@0.16.0"
selene = "Kampfkarren/selene@0.26.1"
wally-package-types = "johnnymorganz/wally-package-types@1.5.1"
stylua = "johnnymorganz/stylua@0.20.0"
luau-lsp = "johnnymorganz/luau-lsp@1.52.1"