local Types = require(script.Parent.Parent:WaitForChild("Types"))

return {
	[1] = {
		Damage = 25,
		Price = 250,

		Image = "rbxassetid://72667726780057",
	},
	[2] = {
		Damage = 50,
		Price = 1500,

		Image = "rbxassetid://119660027367472",
	},
	[3] = {
		Damage = 75,
		Price = 4000,

		Image = "rbxassetid://109815186587002",
	},
	[4] = {
		Damage = 100,
		Price = 15000,

		Image = "rbxassetid://98077211212412",
	},
	[5] = {
		Damage = 150,
		Price = 40000,

		Image = "rbxassetid://71335026328316",
	},
	[6] = {
		Damage = 200,
		Price = 200000,

		Image = "rbxassetid://115698879258357",
	},
	[7] = {
		Damage = 350,
		Price = 850000,

		Image = "rbxassetid://83584774640762",
	},
	[8] = {
		Damage = 750,
		Price = 2500000,

		Image = "rbxassetid://104543473384694",
	},
	[9] = {
		Damage = 1250,
		Price = 10000000,

		Image = "rbxassetid://85888755225488",
	},
	[10] = {
		Damage = 2000,
		Price = 50000000,

		Image = "rbxassetid://111563464863450",
	},
	[11] = {
		Damage = 50000,
		Price = 1,

		Gamepass = 1,

		Image = "rbxassetid://111563464863450",
	},
} :: { [number]: Types.ToolInfo }
