local Types = require("@Shared/Types.luau")

return {
	[1] = {
		Damage = 25,
		Price = 25,

		Image = "",
	},
	[2] = {
		Damage = 50,
		Price = 150,

		Image = "",
	},
	[3] = {
		Damage = 75,
		Price = 400,

		Image = "",
	},
	[4] = {
		Damage = 100,
		Price = 1500,

		Image = "",
	},
	[5] = {
		Damage = 150,
		Price = 4000,

		Image = "",
	},
	[6] = {
		Damage = 200,
		Price = 20000,

		Image = "",
	},
	[7] = {
		Damage = 350,
		Price = 85000,

		Image = "",
	},
	[8] = {
		Damage = 750,
		Price = 250000,

		Image = "",
	},
	[9] = {
		Damage = 1250,
		Price = 1000000,

		Image = "",
	},
	[10] = {
		Damage = 2000,
		Price = 5000000,

		Image = "",
	},
} :: { [number]: Types.ToolInfo }
